export const ADD_CLASSROOM = 'ADD_CLASSROOM'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const ADD_STUDY = 'ADD_STUDY'
export const ADD_SOFTWARE = 'ADD_SOFTWARE'

export const DELETE_CLASSROOM = 'DELETE_CLASSROOM'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
export const DELETE_STUDY = 'DELETE_STUDY'
export const DELETE_SOFTWARE = 'DELETE_SOFTWARE'

export const OCCUPY_TERM = 'OCCUPY_TERM'
export const UNOCCUPY_TERM = 'UNOCCUPY_TERM'
