export const ADD_CLASSROOM = 'ADD_CLASSROOM'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const ADD_STUDY = 'ADD_STUDY'
export const ADD_SOFTWARE = 'ADD_SOFTWARE'

export const DELETE_CLASSROOM = 'DELETE_CLASSROOM'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
export const DELETE_STUDY = 'DELETE_STUDY'
export const DELETE_SOFTWARE = 'DELETE_SOFTWARE'

export const OCCUPY_TERM = 'OCCUPY_TERM'
export const UNOCCUPY_TERM = 'UNOCCUPY_TERM'

export const SELECT_CLASSROOM = 'SELECT_CLASSROOM'

export const SET_EDITING_CLASSROOM = 'SET_EDITING_CLASSROOM'
export const EDIT_CLASSROOM = 'EDIT_CLASSROOM'

export const SET_EDITING_SUBJECT = 'SET_EDITING_SUBJECT'
export const EDIT_SUBJECT = 'EDIT_SUBJECT'

export const SET_EDITING_STUDY = 'SET_EDITING_STUDY'
export const EDIT_STUDY = 'EDIT_STUDY'

export const SET_EDITING_SOFTWARE = 'SET_EDITING_SOFTWARE'
export const EDIT_SOFTWARE = 'EDIT_SOFTWARE'
